version: "3.7"

services:

  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    image: elasticsearch:6.4.2
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    volumes:
      - tina_elk:/usr/share/elasticsearch/data
    networks:
      - internal
      - proxy
    deploy:
      labels:
        - "traefik.backend=elasticsearch"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
        - "traefik.port=9200"
        - "traefik.frontend.rule=Host:elasticsearch.tina.ctg.lu"
        - "traefik.frontend.entryPoints=http, https"
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
  
  kibana:
    image: kibana:6.4.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - proxy
      - internal
    deploy:
      labels:
        - "traefik.backend=kibana"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
        - "traefik.port=5601"
        - "traefik.frontend.rule=Host:kibana.tina.ctg.lu"
        - "traefik.frontend.entryPoints=http, https"
      mode: replicated
      replicas: 1
    healthcheck:
      test: wget -qO- kibana.tina.ctg.lu > /dev/null
      interval: 30s
      retries: 3
  
  
  logstash:
    command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elasticsearch\" ] } }'"
    image: logstash:latest
    ports:
        - "10514:10514/tcp"
        - "10514:10514/udp"
        - "12201:12201/udp"
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 2


networks:
  proxy:
    driver: overlay
    external: true
  internal:
    driver: overlay
    external: true


volumes:
  tina_elk:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/elk"