debug = false
logLevel = "INFO"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false

defaultEntryPoints = [ "http", "https"]


# http should not be redirected to https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      
      

[entryPoints.ping]
  address = ":8082"

[entryPoints.admin]
  address = ":8081"

[rest]
 entryPoint = "ping"

[ping]
  entryPoint = "ping"

[api]
  entryPoint = "admin"
  dashboard = true
  [web.statistics]


[acme]
 email = "aureussz@gmail.com"
 storage = "/etc/traefik/acme.json"
 entryPoint = "https"
 onHostRule = true

    
 [acme.httpChallenge]
 entryPoint = "http"